### ISSUE TITLE
Unable to link github

### ISSUE THREAD

**Issue by Scarycrumb45** [punitda/ssh-git#97]
```
TypeError: Cannot read property 'id' of null
    at /opt/ssh-git/resources/app.asar/node_modules/electron-better-ipc/source/main.js:10:98
    at new Promise (<anonymous>)
    at EventEmitter.ipc.callRenderer (/opt/ssh-git/resources/app.asar/node_modules/electron-better-ipc/source/main.js:9:54)
    at EventEmitter.ipc.callFocusedRenderer (/opt/ssh-git/resources/app.asar/node_modules/electron-better-ipc/source/main.js:46:44)
    at Object.handleAppURL (/opt/ssh-git/resources/app.asar/src/main/helpers.js:24:7)
    at App.<anonymous> (/opt/ssh-git/resources/app.asar/src/main/index.js:55:13)
    at App.emit (events.js:194:13)
    at App.EventEmitter.emit (domain.js:469:20)
    at App.emitter.emit (/opt/ssh-git/resources/app.asar/node_modules/@sentry/electron/dist/main/integrations/electron.js:55:20)
    at App.<anonymous> (/opt/ssh-git/resources/app.asar/src/main/index.js:27:9)
```

**Comment by punitda** [comment]
@Scarycrumb45 Can you please provide more context about this error? At which step it fails for you when setting up SSH for Github account?
